Issue #113 taskCard UI
snowballDevs/kandoo pull request #130
Opened 2023-08-30 21:46 UTC by Michelle-932

## Description

Fixed first half of issue #113 to re-style the task cards to reflect priority level. (Adding assignees and having instant re-rendering are not included.)

My updated readme.md and styleguide.md files are also included, so you can discard my previous unmerged PR. 

## Related Issue

-   [ ] Is this related to a specific issue? Is so please specify: Issue #113 taskCard UI

## Type of Changes

Use a check for ✓ the following type of changes:

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

[If applicable, include a picture of the behavior before the changes were made. I.e. a screenshot of the behavior before the changes were made.]

### After

![image](https://i.imgur.com/p9xezw6.png)

## Testing Steps / QA Criteria

Additional testing needs to be done for stability reasons -- this update is extremely unstable and potentially fails when any unrelated changes to the file are made. (No idea why.)

## Checklist:

-   [ ✓] This PR is up to date with the development branch, and merge conflicts have been resolved
-   [ ✓] My code follows the style guidelines of this project
-   [✓ ] I have executed npm run lint and resolved any outstanding errors. 
-   [ ✓] I have performed a self-review of my own code
-   [✓ ] I have commented my code, particularly in hard-to-understand areas
-   [ ✓] My changes generate no new warnings

2023-08-31 06:01 UTC, IntelliJinceTech requested changes
I was having issues seeing the accent on the card for some reason so I changed the code with just conditional rendering instead of using an object. Let me know if that works for you! 

Also added some comments to the markdown

2023-08-31 14:31 UTC, Michelle-932 commented on README.md
> +* Other routes as needed for columns, tasks, and comments.
Ok that's fine! We can delete that part. I was still getting the hang of who exactly the audience will be.

2023-08-31 22:55 UTC, mjbramich commented on README.md
> +* Other routes as needed for columns, tasks, and comments.
Hey Guys, 
Here is some good reading.
https://tailwindcss.com/docs/content-configuration#dynamic-class-names. 
I like the idea of mapping classNames to an object like they show. Slightly adjusted the code and it works
![image](https://github.com/snowballDevs/kandoo/assets/105207353/278c4874-e081-4d17-9731-8033f3a4339b)
![image](https://github.com/snowballDevs/kandoo/assets/105207353/ad2b97c0-947b-4101-99c5-f53d6ec7f108)

There is also a bug now where when we drag a task, we lose the contents of the task. Im not sure what has changed, so need to fix that as well.

2023-09-01 18:36 UTC, Michelle-932 commented
Yes, these changes work great! I was on the right track but thanks for coming up with the conditional rendering. 
I incorporated your changes in the latest commit, they should be showing up there.

2023-09-14 16:19 UTC, IntelliJinceTech commented
Looks like I'm getting this weird bug: 

<img width="1470" alt="image" src="https://github.com/snowballDevs/kandoo/assets/52391491/4f29de14-43a3-420f-87cf-aa3436e6809f">

@Michelle-932 are you around to address that? If not, someone else on the team will have to take over this PR.

2023-09-14 16:31 UTC, Michelle-932 commented
Yes, please reassign this PR. Thank you

On Thu, Sep 14, 2023 at 11:19 AM Christopher Jin ***@***.***>
wrote:

> Looks like I'm getting this weird bug:
> [image: image]
> <https://user-images.githubusercontent.com/52391491/268042883-4f29de14-43a3-420f-87cf-aa3436e6809f.png>
>
> @Michelle-932 <https://github.com/Michelle-932> are you around to address
> that? If not, someone else on the team will have to take over this PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/snowballDevs/kandoo/pull/130#issuecomment-1719760733>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2PAZJ7N6EQTFJAVJY7N3FLX2MVAVANCNFSM6AAAAAA4FENXT4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-26 00:49 UTC, closed without merging